### ISSUE TITLE
Check URL access

### ISSUE THREAD

**Issue by Titogelo** [WELTEN/dojo-ibl-v2#20]
If you access -via the URL- another project (a project in which you are not project owner) you still have access. 

I was editing a project and I logged out. When I logged in again I was redirected to the project again. Although I was not project owner I was able to see it and modify it.  

Either with a firebase rule or checking programmatically if you have the right to access that url will solve the issue.

**Comment by rafaelklaessen** [comment]
I'll do both.
I'll create a separate issue for the firebase rules, and I'll add the owner checking after that.
Please be aware that at this point pretty much everything isn't secure yet due to the lack of firebase rules.

**Comment by Titogelo** [comment]
Okay. 

Yes sure!, I just added it there to not forget. I know you have that in mind but it is also good to have it written down here ;-)

**Comment by Titogelo** [comment]
This comment relates to https://github.com/WELTEN/dojo-ibl-v2/issues/10 in which a project owner can add or remove more owners to the project.

Given the situation that User A (project owner) is editing the project and User B (also project owner) remove the owner rights to User A. What will happen to User A that was seeing/editing the project. 

Different alternatives: 
1) User A is redirected to /home
2) User A remains in the project editor view but is not able to save any information.

**Comment by rafaelklaessen** [comment]
Well, since the to-be-made system that checks for access would update real-time, the edit project page would just change into a no access text.
