### ISSUE TITLE
Add activity comments

### ISSUE THREAD

**Issue by rafaelklaessen** [WELTEN/dojo-ibl-v2#29]

**Comment by Titogelo** [comment]
This must include also the possibility to add files (images, docs, videos...) and store them firebase storage. 

ATM in DojoIBL v1 for the pictures I have a kind of carousel that you can visualize fullscreen all the pictures uploaded in one activity. 

BTW, if you use DojoIBL v1 from the browser of the mobile phone you can directly take a picture and upload it.

**Comment by rafaelklaessen** [comment]
I treat that as a separate issue: #32
