### ISSUE TITLE
Just an enter should count as empty in inputs

### ISSUE THREAD

**Issue by rafaelklaessen** [WELTEN/dojo-ibl-v2#34]
Also, strip preceding and trailing enters everywhere.

**Comment by Titogelo** [comment]
Could you please add more info here? Usually, your issues are self-explanatory but here I am not sure to what you are referring to. Thanks!

**Comment by rafaelklaessen** [comment]
Currently if you enter an enter (\n) in an input, that doesn't count as the input being empty (but it should).
