### ISSUE TITLE
TypeError: Cannot read property 'code' of null

### ISSUE THREAD

**Issue by Titogelo** [WELTEN/dojo-ibl-v2#43]
This is the last commit I synced: https://github.com/WELTEN/dojo-ibl-v2/commit/4ecd0929676b0890ec6d5726c47c8b062a0e82d0

When using this version, there is an error in the following line:

https://github.com/WELTEN/dojo-ibl-v2/blob/4ecd0929676b0890ec6d5726c47c8b062a0e82d0/src/components/GroupListItem.js#L23

Please check ;-)

**Comment by rafaelklaessen** [comment]
Could you please give me the ID (like the Firebase key in the URL) of the group you're trying to access?

**Comment by Titogelo** [comment]
sure. ahhh maybe you are right maybe and the problem is due to an old group and project. 

-Kz5mIWgwhskMDrULb7I

http://localhost:3000/projects/-Kz5mIWgwhskMDrULb7I/edit

**Comment by rafaelklaessen** [comment]
Yeah I recently did some breaking changes (for the reordering) that might in some way affect this too.
I'll look into it tomorrow.

**Comment by rafaelklaessen** [comment]
Turns out I deleted the group. The project was invalid too so I've just deleted it.

**Comment by Titogelo** [comment]
Okay. How did you solve this issue here? 

I guess now if someone access a wrong (old) ID (in whatever page) he/she will be redirected to the error page right?

**Comment by rafaelklaessen** [comment]
No, this situation is not possibly recreatable by a user (or at least it shouldn't be). It occurred because the project was referring to a nonexisting group because I deleted it via the Firebase console.
If a user deletes a group the project no longer refers to it.
